GET http://localhost:3000/api/produtos

###
GET http://localhost:3000/api/produtos/3

###
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
    "nome": "produto3",
    "preco": 70
}

###
PUT http://localhost:3000/api/produtos/3
Content-Type: application/json

{
    "nome": "produto3",
    "preco": 72
}

###
DELETE http://localhost:3000/api/produtos/3